services:

  # PostgreSQL 数据库服务
  postgres-db:
    image: registry.cn-shanghai.aliyuncs.com/odoo-1di0t/postgres:16
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${DB_PASS:-odoo}
      - POSTGRES_USER=${DB_USER:-odoo}
      #      - POSTGRES_DB=lamp_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    #    ports:
    #      - "5432:5432"  # 映射 PostgreSQL 的端口
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata  # 数据持久化

  # Redis 服务
  redis-server:
    image: registry.cn-shanghai.aliyuncs.com/odoo-1di0t/redis:alpine  # 使用 Redis 的轻量级 alpine 镜像
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${RD_PASS:-odoo}
    volumes:
      - ./cache:/data
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "8"

  odoo-backend-19:
    build:
      context: .
      dockerfile: ./Dockerfile.odoo
    image: backend:19
    restart: always
    container_name: "odoo-backend-19"
    depends_on:
      - postgres-db
      - redis-server
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./odoo-files:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=postgres-db
      - USER=${DB_USER:-odoo}
      - PASSWORD=${DB_PASS:-odoo}
      - ODOO_HTTP_SOCKET_TIMEOUT=${ODOO_HTTP_SOCKET_TIMEOUT}
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "8"
