services:
  database-18:
    image: registry.cn-shanghai.aliyuncs.com/odoo-1di0t/postgres:16
    container_name: "database-18"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${DB_PASS:-odoo}
      - POSTGRES_USER=${DB_USER:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "8"

  backend-18:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend:18
    container_name: "backend-18"
    depends_on:
      - database-18
      - cache-18
    ports:
      - "28069:8069"
      - "28072:8072"
    volumes:
      - ./files:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=database-18
      - USER=${DB_USER:-odoo}
      - PASSWORD=${DB_PASS:-odoo}
      - ODOO_HTTP_SOCKET_TIMEOUT=${ODOO_HTTP_SOCKET_TIMEOUT}
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "8"

  cache-18:
    image: registry.cn-shanghai.aliyuncs.com/odoo-1di0t/redis:7.2-alpine
    container_name: "cache-18"
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${RD_PASS:-odoo}
    volumes:
      - ./cache:/data
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "8"
