{
    "name": "Lamp Order",
    "summary": "Lamp Order",
    "author": "1di0t",
    "license": "AGPL-3",
    'depends': ['base', 'web', 'product', 'stock', 'sale', 'sale_management', 'account', 'mail', 'repair'],
    "data": [
        "security/ir.model.access.csv",
        "security/res_group.xml",
        "data/product_product.xml",
        "views/sale_order_view.xml",
        "views/res_partner_view.xml",
        "views/stock_warehouse_view.xml",
        "views/product_template_view.xml",
        "views/stock_quant_view.xml",
        "views/product_category_view.xml",
        "views/stock_location_view.xml",
        # "views/product_image_view.xml",
        "views/stock_picking_view.xml",
        # "views/loyalty_view.xml",
        "views/report_stock_quantity_view.xml",
        "report/stock_report_forecast_view.xml",
        "wizards/stock_report_wizard_view.xml",
        "views/menu.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'lamp_order/static/src/views/xml/form_controller.xml',
        ],
    },
    "installable": True,
    "auto_install": False,
}
