[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
server_wide_modules = base,web
workers = 6
redis_host = 0.0.0.0
redis_port = 6379
redis_password = 123456
redis_cache_prefix = lamp:cache
redis_cache_db = 3
admin_passwd = $pbkdf2-sha512$600000$LuVcC4EQ4hzDWOtdS6l1Tg$SIhn6nO077686pRfOIdT2MxNDP0Cr/92GxjTNHQO0EzxJkG0gkh8CZtkB07kTfcZY/HZzqX6397vu9FW9JjmPw
